//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxVsCsv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxVsCsv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2025 .
        /// </summary>
        internal static string CopyrightMessage {
            get {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while translating {0}.
        /// </summary>
        internal static string ErrorWhileTranslating {
            get {
                return ResourceManager.GetString("ErrorWhileTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For conversion to CSV: .
        /// </summary>
        internal static string ForConversionToCsv {
            get {
                return ResourceManager.GetString("ForConversionToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For translation: .
        /// </summary>
        internal static string ForTranslation {
            get {
                return ResourceManager.GetString("ForTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For translation with argos: .
        /// </summary>
        internal static string ForTranslationWithArgos {
            get {
                return ResourceManager.GetString("ForTranslationWithArgos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For translation with LibreTranslate: .
        /// </summary>
        internal static string ForTranslationWithLibreTranslate {
            get {
                return ResourceManager.GetString("ForTranslationWithLibreTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For translation with LibreTranslate: .
        /// </summary>
        internal static string ForTranslationWithLLM {
            get {
                return ResourceManager.GetString("ForTranslationWithLLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For updating .Resx files: .
        /// </summary>
        internal static string ForUpdatingResxFiles {
            get {
                return ResourceManager.GetString("ForUpdatingResxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by AI.
        /// </summary>
        internal static string GeneratedByAi {
            get {
                return ResourceManager.GetString("GeneratedByAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included in a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM call failed: {0}.
        /// </summary>
        internal static string LlmCallFailedMessage {
            get {
                return ResourceManager.GetString("LlmCallFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing JSON response from LLM: {0}.
        /// </summary>
        internal static string LlmErrorParsingJsonMessage {
            get {
                return ResourceManager.GetString("LlmErrorParsingJsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while running HTTP request to LLM: {0}.
        /// </summary>
        internal static string LlmHtttpResponseErrorMessage {
            get {
                return ResourceManager.GetString("LlmHtttpResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM response doesn&apos;t contain a valid &apos;message&apos; object in first &apos;choices&apos; element:.
        /// </summary>
        internal static string LlmInvalidMessageElementMessage {
            get {
                return ResourceManager.GetString("LlmInvalidMessageElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM response doesn&apos;t contain a valid &apos;choices&apos; element {0}.
        /// </summary>
        internal static string LlmMisssingChoicesElementMessage {
            get {
                return ResourceManager.GetString("LlmMisssingChoicesElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated {0}.
        /// </summary>
        internal static string TranslatedCultureString {
            get {
                return ResourceManager.GetString("TranslatedCultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string UseWordWrap {
            get {
                return ResourceManager.GetString("UseWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: loading of entries from following file failed: {0}.
        /// </summary>
        internal static string WarningLoadingEntriesFromFileFailed {
            get {
                return ResourceManager.GetString("WarningLoadingEntriesFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no entries found in file {0}.
        /// </summary>
        internal static string WarningNoEntriesInFile {
            get {
                return ResourceManager.GetString("WarningNoEntriesInFile", resourceCulture);
            }
        }
    }
}
