//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxVsCsv.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxVsCsv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright © 2025-2026  ähnelt.
        /// </summary>
        internal static string CopyrightMessage {
            get {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while translating {0} ähnelt.
        /// </summary>
        internal static string ErrorWhileTranslating {
            get {
                return ResourceManager.GetString("ErrorWhileTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For conversion to CSV:  ähnelt.
        /// </summary>
        internal static string ForConversionToCsv {
            get {
                return ResourceManager.GetString("ForConversionToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For translation:  ähnelt.
        /// </summary>
        internal static string ForTranslation {
            get {
                return ResourceManager.GetString("ForTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For translation with argos:  ähnelt.
        /// </summary>
        internal static string ForTranslationWithArgos {
            get {
                return ResourceManager.GetString("ForTranslationWithArgos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For translation with LibreTranslate:  ähnelt.
        /// </summary>
        internal static string ForTranslationWithLibreTranslate {
            get {
                return ResourceManager.GetString("ForTranslationWithLibreTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For translation with LibreTranslate:  ähnelt.
        /// </summary>
        internal static string ForTranslationWithLLM {
            get {
                return ResourceManager.GetString("ForTranslationWithLLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For updating .Resx files:  ähnelt.
        /// </summary>
        internal static string ForUpdatingResxFiles {
            get {
                return ResourceManager.GetString("ForUpdatingResxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generated by AI ähnelt.
        /// </summary>
        internal static string GeneratedByAi {
            get {
                return ResourceManager.GetString("GeneratedByAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included in a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LLM call failed: {0} ähnelt.
        /// </summary>
        internal static string LlmCallFailedMessage {
            get {
                return ResourceManager.GetString("LlmCallFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while parsing JSON response from LLM: {0} ähnelt.
        /// </summary>
        internal static string LlmErrorParsingJsonMessage {
            get {
                return ResourceManager.GetString("LlmErrorParsingJsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while running HTTP request to LLM: {0} ähnelt.
        /// </summary>
        internal static string LlmHtttpResponseErrorMessage {
            get {
                return ResourceManager.GetString("LlmHtttpResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LLM response doesn&apos;t contain a valid &apos;message&apos; object in first &apos;choices&apos; element: ähnelt.
        /// </summary>
        internal static string LlmInvalidMessageElementMessage {
            get {
                return ResourceManager.GetString("LlmInvalidMessageElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LLM response doesn&apos;t contain a valid &apos;choices&apos; element {0} ähnelt.
        /// </summary>
        internal static string LlmMisssingChoicesElementMessage {
            get {
                return ResourceManager.GetString("LlmMisssingChoicesElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translated {0} ähnelt.
        /// </summary>
        internal static string TranslatedCultureString {
            get {
                return ResourceManager.GetString("TranslatedCultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string UseWordWrap {
            get {
                return ResourceManager.GetString("UseWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: loading of entries from following file failed: {0} ähnelt.
        /// </summary>
        internal static string WarningLoadingEntriesFromFileFailed {
            get {
                return ResourceManager.GetString("WarningLoadingEntriesFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: no entries found in file {0} ähnelt.
        /// </summary>
        internal static string WarningNoEntriesInFile {
            get {
                return ResourceManager.GetString("WarningNoEntriesInFile", resourceCulture);
            }
        }
    }
}
